In [3]:
import numpy as np
import matplotlib.pyplot as plt

Pertama jika ada snipad maka copy dulu ke google collab

In [2]:
mX = [
        [
            [10, 2, -6],
            [-1, 4, 2],
            [2, 3, 6]
        ],
        [
            [-5, 2, -8],
            [4, -3, -9],
            [-8, -10, 9]
        ],
        [
            [10, -5, 3, 0],
            [3, -9, 2, -2],
            [-8, 0, 17, -4],
            [3, -3, -8, -15]
        ],
]

mY = [
    [17, -4, -12],
    [13, -7, -2],
    [9, 10, -10, -18]
]


In [4]:
# 1
def checkDiagonallyDominant(x):
  # disini dia akan ngecek apakah diagonalnya lebih besar dari hasil penjumlahan yang bukan diagonal
  x = np.array(x)
  diag = np.diag(np.abs(x))
  sumWithDiag = np.sum(np.abs(x), axis = 1) #kita akan jumlahin ke samping maka dia axisnya 1
  # kalau mau jumlahinnya atas ke bawah maka axisnya 0
  sumWithoutDiag = sumWithDiag - diag
  # print(sumWithoutDiag)

# kalau mau print printnya berarti berada di tengah ini

  if np.all(diag > sumWithoutDiag):
    print("Diagonally Dominant")
    return True
  else:
    return False

checkDiagonallyDominant(mX[0]) #kita perlu masukin array ke berapanya 


Diagonally Dominant


True

In [5]:
#2
# buat function buat gauss seidel
# dia nerima x dan y

def gaussSeidel(x,y,max,epsilon):
  x = np.array(x)
  y = np.array(y)
  
  if (not checkDiagonallyDominant(x)): #jika dia tidak diagonal dominant maka return false / tidak lanjut
    return False

  # bikin dulu ada diag
  diag = np.diag(x) #ini diagonalnya digunakan untuk membagi
  x = -x #ini untuk pindah ruas maka ganti tanda

  np.fill_diagonal(x,0) #kosongin pembaginya agar tidak ikut kehitung

  # bikin array untuk iterasi
  x_before = np.zeros(x.shape[0]) #ini buat np baru yang isinya 0
  # np.shape ini untuk tau matriks kita isinya berapa kali berapa

  for i in range(max): #dia mulai dari 0 sampai max
    x_new = np.array(x_before)
    # dibawah ini cuma tambahan aja buat ngecek
    print("INI X NEW")
    print(x_new)
    print("=========")
    for j, row in enumerate(x) : #j buat akses satu persatunya dan row ini untuk akses barisnya
      # j ini untuk akses jalannya satu persatu dan row itu untuk akses barisnya
      print(j,row)
      #a = (17 - 2b + 6c)/10
      x_new[j] = (y[j] + np.dot(row, x_new))/diag[j]

    # ngecheck epsilonnya
    distance =  np.sqrt(np.dot(x_new - x_before, x_new - x_before))

    print(f"{i} : {x_new}")
    #cek misalnya si distance < epsilon kita maka tinggal return
    if distance < epsilon:
      return x_new
    # jika dia ga masuk ke if nya maka
    x_before = x_new
    
  # return False kalau gapakae return false maka akan munculnya none

In [6]:
# print("Shape")
# x = np.array([0,1,2])
# print(x.shape)

# print(" ")

print("Gauss Seidel")
# buat loopingin nested arraynya
# pertama looping sebanyak matriksnya
for i, (x,y) in enumerate(zip(mX,mY)) : #ini dia mau akses mX dan mY nya secara bersamaan
  # zip ini untuk akses x,y dan pasangannya x itu akses di mX dan y itu akses di mY
  gaussSeidel(x, y, 5, 0.01456)

  print("\nPrint Gauss Seidelnya")
  print(gaussSeidel(x,y,5,0.01456))

Gauss Seidel
Diagonally Dominant
INI X NEW
[0. 0. 0.]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
0 : [ 1.7        -0.575      -2.27916667]
INI X NEW
[ 1.7        -0.575      -2.27916667]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
1 : [ 0.4475      0.25145833 -2.27489583]
INI X NEW
[ 0.4475      0.25145833 -2.27489583]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
2 : [ 0.28477083  0.20864062 -2.19924392]
INI X NEW
[ 0.28477083  0.20864062 -2.19924392]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
3 : [ 0.33872552  0.18430334 -2.20506018]
INI X NEW
[ 0.33872552  0.18430334 -2.20506018]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
4 : [ 0.34010322  0.1875559  -2.20714569]

Print Gauss Seidelnya
Diagonally Dominant
INI X NEW
[0. 0. 0.]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
0 : [ 1.7        -0.575      -2.27916667]
INI X NEW
[ 1.7        -0.575      -2.27916667]
0 [ 0 -2  6]
1 [ 1  0 -2]
2 [-2 -3  0]
1 : [ 0.4475      0.25145833 -2.27489583]
INI X NEW
[ 0.4475      0.25145833 -2.27489583]
0 [ 0 -2  6]
1 [ 1  0 -2]
2

In [ ]:
# SNIPAD NO 3
lX = [1, 5, 7, 2, 3, 9, 10, 4, 6, 8]
lY = [34, 51, 80, 25, 90, 76, 100, 11, 45, 62]


In [ ]:
#3
# bikin dulu yang berapa yaitu
lX = np.array(lX)
lY = np.array(lY)

# bikin a nya terlebih dahulu
A = np.vstack([lX, np.ones(len(lX))]).T #isinya ngambil dari X nya
print(A)
Y = np.vstack(lY)
print(Y)

# CARA PENULISAN BETA 
# VERSI 1
beta = np.dot(np.dot(np.linalg.inv(np.dot(A.T,A)), A.T), Y)
print(beta) 

# VERSI 2
# beta1 = np.dot(A.T,A)
# beta2 = np.linalg.inv(beta1)
# beta3 = np.dot(beta2, A.T)
# beta4 = np.dot(beta3, Y)
# print(beta4)

# hasil yang pertama itu jadi m
m =  beta[0]
# hasil yagn kedua itu jadi c
c = beta[1]

#y = m * lX + c
y = m * lX + c
plt.plot(lX, lY, 'go') #green o
plt.plot(lX, y, 'b-') #blue garis
plt.show()

In [ ]:
#4
from sympy import *
a = symbols('a')

f1 = 7*a**4 - 3*a**2 + a
df1 = diff(f1,a)
df1 = lambdify(a, df1, 'numpy')
f1 = lambdify(a, f1, 'numpy')

f2 = 8*a**6 + 5*a**4 - 2
df2 = diff(f2,a)
df2 = lambdify(a, df2, 'numpy')
f2 = lambdify(a, f2, 'numpy')

# Pertama bikin turunannya terlebih dahulu
# bisa pake library atau manual
# jika pakai library maka pakai yang di atas

print(f2(2), df2(2))

590 1696


In [ ]:
def newton_raphson(f, df, tolerance, max, x0): #x0 ini adalah first guess
  #nilainya harus lebih kecil dari tolerance
  if max == 0:
    print("Max Iteration Reached")
    return False
  
  if np.abs(f(x0)) < tolerance:
    print(x0)
    return True
  
  else:
    return newton_raphson(f,df, tolerance, max-1, x0 - (f(x0) / df(x0)))

In [ ]:
newton_raphson(f1, df1, 0.006541, 5, 1)
newton_raphson(f2, df2, 0.006541, 5, 1)

In [ ]:
#5
fr = lambda x: 3*x**4 - 7*x**2 + 5

# ambil batas atas dan batas bawahnya
a = -4 #batas bawahnya
b = 3 #batas atas
n = 30 #jumlah gridnya

x = np.linspace(a,b,n)
width = (b-a)/(n-1)

xLeft = x[:-1] #ini kita ambil dari awal sampai index terakhir tetapi dikurangi 1 index / sampai index sebelum index terakhir 
xRight = x[1:]
xMid = (xLeft + xRight)/2

yLeft = fr(xLeft)
yRight = fr(xRight)
yMid = fr(xMid)

# cari nilai left riemann, right riemann
leftRiemann = width * (sum(np.abs(yLeft)))
rightRiemann = width * (sum(np.abs(yRight)))
midRiemann = width * (sum(np.abs(yMid)))

print("Left Riemann :", leftRiemann)
print("Right Riemann :", rightRiemann)
print("Mid Riemann :", midRiemann)


#Trapezoid
yTrapezoid = fr(x)
# trapezoid ini ikuti rumus trapesium
trapezoid = (np.sum(np.abs(yTrapezoid[:-1])) + np.sum(np.abs(yTrapezoid[1:]))) * width /2.
print("Trapezoid :",trapezoid)